### ISSUE TITLE
Bug list 1

### ISSUE THREAD

**Issue by MustacheMan2** [cuzitsjonny/JALUS#3]
General:

Switch Minifigure button often does not work and kicks to main menu

Spawning in multiple entities will result in a server crash

equipping/unequipping very buggy

Multiple choice reward missions will give all rewards; tutorial doesn’t always tell you to equip the right weapon

Universe score count improperly working

Venture Explorer:

Tutorial restarts on game restart (may be intended this way)

Rocket drops unusual

Imagination orbs sometimes respawn on restart

Bouncepad dialogue effect often too quiet or missing

Some rocket parts do not allow you to delete them

Nimbus station:

Destroying shipment crate crashes server

Gnarled forest:

Pirate hiding in cave missing

Maelstrom pirates trapped behind wall object in brig rock

Entering pirate area and/or accepting quests crashes server OR kicks to main menu.

Sound broken. Only ambient sounds work. Sound stops working in all worlds for remainder of session

Attempting to smash a banana tree crashes server

Forbidden Valley:

Hitting candles will crash the server

**Comment by RaineBannister** [comment]
You should probably break this out into multiple issues. Lumping then all together makes it impossible to manage and address

**Comment by RaineBannister** [comment]
Rocket crates will not drop items, as that is powered by a script, and a scripting system has not been implemented

**Comment by RaineBannister** [comment]
Tutorial state doesn't persist as the flag probably isn't set

**Comment by cuzitsjonny** [comment]
> Rocket crates will not drop items, as that is powered by a script, and a scripting system has not been implemented

JALUS. WILL. NEVER. SUPPORT. LUA!

**Comment by WesleyJB** [comment]
> > Rocket crates will not drop items, as that is powered by a script, and a scripting system has not been implemented
> 
> JALUS. WILL. NEVER. SUPPORT. LUA!

I will add scripting at some point but it won't be LUA.

**Comment by averysumner** [comment]
Why not Lua? I mean besides the fact that arrays start at 0, it’s a pretty
solid scripting language...

**Comment by WesleyJB** [comment]
I really don't know. Maybe I will use Lua. Not really sure now, as that's a long ways down the road.
